### PR TITLE
adds speed slider

### PR DESCRIPTION
**Pull request by elkhorn360**

### CODE REVIEW

**Comment by nicodelpiano** [comment]
Awesome work @elkhorn360! Really like the slider approach!

Unfortunately, there was someone else working on this issue and I prioritized that. However, I also would like to merge your work, would you mind integrating the speed input field that's now on master with yours? Like using the approach that it's now (the input field) and your slider at the same time, they can be next to each other. Feel free to adjust the speed as well.

If you don't want to do this, it's fine, I'll resolve the conflicts and merge your PR and do the integration later.

Let me know your thoughts,

thanks!

**Comment by elkhorn360** [comment]
@nicodelpiano Thanks. Yeah sure, I'll do that.

**Comment by elkhorn360** [comment]
@nicodelpiano I updated the PR for the slider to work with input field

**Review by nicodelpiano — APPROVED** [review]
Awesome job @elkhorn360! Thanks! 🥇

**Pull request merged**
