### PR TITLE
Fix formatting and template literals

### PR DESCRIPTION
**Pull request by CoryWritesCode**
~Satisfies #9~

~Looking at the algorithms there isn't a specific way of finding out how they are going to be sorted since they can take a different number of steps if you click the same sort over and over again.~

~This makes the ability to show how many steps it's going to take impossible so I just added a step counter.~

Other stuff:
my linter fixed some whitespace and styling (can revert if needed)
and I made the strings [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) for a cleaner read.

### CODE REVIEW

**Comment by nicodelpiano** [comment]
Hi @CoryWritesCode, thanks for the PR!

Hmm, from your attached gif I noticed you are not seeing the styles of the page properly 😩 . I just added the css file missing (there was a sass file but needs compilation to css in order to work).

> This makes the ability to show how many steps it's going to take impossible so I just added a step counter.

For this, you could've used the `drawSteps` function, and there you have the `steps` variable which has the total steps of the current algorithm 😄 .

Although you code looks good to me, I already merged #12 that implements this and solves the issue... but I liked your template literals fix, so if you can submit only that in the PR I'll merge it!

Thanks!

**Comment by CoryWritesCode** [comment]
There you go @nicodelpiano ! Thanks!

**Comment by nicodelpiano** [comment]
@CoryWritesCode thanks! can you remove the ones in the html 🙏 , and that'll be it! Just leave the ones in `app.js`.

**Review by nicodelpiano — APPROVED** [review]
@CoryWritesCode actually, let's leave as it is, great job! 🥇

**Pull request merged**
